name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["win-x64", "osx-x64", "linux-x64", "linux-arm64", "linux-arm"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.400

      - name: Produce build
        run: |
          cd EasyCommands
          dotnet build
